apiVersion: "v1"
kind: "Service"
metadata:
  name: "proxy-print"
  labels:
    app: "proxy-print"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "proxy-print"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "proxy-print"
  labels:
    app: "proxy-print"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "proxy-print"
  template:
    metadata:
      labels:
        app: "proxy-print"
    spec:
      containers:
        - name: "proxy-print"
          image: "jcorreamo/fiberco-proxy-print:v4"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"